spring:
  application:
    name:
      demo
# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
# 应用服务 WEB 访问端口
server:
  port:
    8080
service:
  ip: 127.0.0.1
  port: 80